---
services:
  redis:
    image: "redis/redis-stack:latest"
    restart: always
    ports:
      - "6380:6379"

  oss_redis:
      image: "redis:latest"
      restart: always
      ports:
        - "6381:6379"
