[tool.poetry]
name = "redis-om"
version = "0.0.1"
description = "A high-level library containing useful Redis abstractions and tools, like an ORM and leaderboard."
authors = ["Andrew Brookins <andrew.brookins@redis.com>"]
maintainers = ["Andrew Brookins <andrew.brookins@redis.com>"]
license = "BSD-3-Clause"
readme = "README.md"
repository = "https://github.com/redis-developer/redis-om-python"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Topic :: Database :: Front-Ends"
]

[tool.poetry.dependencies]
python = "^3.8"
redis = "^3.5.3"
aioredis = "^2.0.0"
pydantic = "^1.8.2"
click = "^8.0.1"
six = "^1.16.0"
pptree = "^3.1"
types-redis = "^3.5.9"
types-six = "^1.16.1"
python-ulid = "^1.0.3"
python-dotenv = "^0.19.1"

[tool.poetry.dev-dependencies]
mypy = "^0.910"
pytest = "^6.2.4"
ipdb = "^0.13.9"
pylint = "^2.11.1"
black = "^21.9b0"
isort = "^5.9.3"
flake8 = "^4.0.1"
bandit = "^1.7.0"
coverage = "^6.1.1"
pytest-cov = "^3.0.0"
pytest-xdist = "^2.4.0"
twine = "^3.4.2"
email-validator = "^1.1.3"
tox = "^3.24.4"
tox-pyenv = "^1.1.0"

[tool.poetry.scripts]
migrate = "redis_om.model.cli.migrate:migrate"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
